name: Deploy to Aliyun OSS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build React App
        run: npm run build
        
      - name: Setup aliyun ossutil
        run: |
          wget https://gosspublic.alicdn.com/ossutil/1.7.14/ossutil64
          chmod 755 ossutil64
          ./ossutil64 config \
            -e ${{ secrets.ALIYUN_OSS_ENDPOINT }} \
            -i ${{ secrets.ALIYUN_ACCESS_KEY_ID }} \
            -k ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
          
      - name: Upload files to OSS
        run: |
          ./ossutil64 cp -r build/ oss://${{ secrets.ALIYUN_OSS_BUCKET }}/ --include "*.html" --include "*.js" --include "*.css" --include "*.json" --include "*.png" --include "*.jpg" --include "*.jpeg" --include "*.gif" --include "*.svg" --include "*.ico" --include "*.woff" --include "*.woff2" --include "*.ttf" --include "*.eot" --force
          ./ossutil64 set-meta oss://${{ secrets.ALIYUN_OSS_BUCKET }}/index.html "Cache-Control:no-cache" --recursive
          ./ossutil64 set-meta oss://${{ secrets.ALIYUN_OSS_BUCKET }}/*.html "Content-Type:text/html" --recursive